spring:
  application:
    name: handong-ut-carpool
  config:
    import:
      - classpath:/yaml/application-keys.yaml
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    #hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: Asia/Seoul

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha